### ISSUE TITLE
Timestamp formatting issues? (or is it just me doing something stupid?)

### ISSUE THREAD

**Issue by asalerno1964** [clyall/FormEmailer#11]
I copied these formats from my old FormEmailer email templates (THANK YOU for making this new one), I've been playing with them for a little while and just cannot seem to get them to work.

This format:
`   #Timestamp|M/d/yyyy H:mm:ss#`
displays as:
`   Tue May 14 2019 15:29:24 GMT-0400 (EDT)`
I expected:
`   5/14/2019 3:29:24`

This format:
`   #Timestamp|yyyy-MM-dd HH:mm:ss#`
displays as:
`   Tue May 14 2019 15:29:24 GMT-0400 (EDT)`
I expected:
`   2019-05-14 15:29:24`

Or did I just read the new instructions incorrectly?

Thanks

**Comment by clyall** [comment]
In your status column, do you see any error messages? Or do they all just say "Email Sent"?

**Comment by asalerno1964** [comment]
Sorry I missed that, the status column says:

**Comment by asalerno1964** [comment]
Apologies, sorry I missed that.  The status column says:

> Error formatting date field: Timestamp|M/d/yyyy H:mm:ss; Error formatting field: Timestamp|M/d/yyyy H:mm:ss; Email1 sent; Error formatting date field: Timestamp|yyyy-MM-dd HH:mm:ss; Error formatting field: Timestamp|yyyy-MM-dd HH:mm:ss; Error formatting date field: Timestamp|yyyy-MM-dd HH:mm:ss; Error formatting field: Timestamp|yyyy-MM-dd HH:mm:ss; Email2 sent

**Comment by clyall** [comment]
If FormEmailer finds a bad formatting for a timestamp, it defaults back to GMT time (which is what is happening here).

I have not actually played with the time formatting portion of this much, but I will look at your spreadsheet in particular to see if this is a FormEmailer bug or a misconfiguration on your part

**Comment by clyall** [comment]
Hi there,

It looks like your Google Sheet did not have a timezone assigned in the Spreadsheet Settings.

The code for date formatting will check your timezone; since it was not set, it was defaulting back to GMT-0400 (EDT) with a default timestamp layout.

I updated the timezone on your sheet, and all the emails went through without errors. For more information, you can read here:
https://support.google.com/docs/answer/58515?co=GENIE.Platform%3DDesktop&hl=en

**Comment by asalerno1964** [comment]
Thank you!!!
