### ISSUE TITLE
Empty text in zip

### ISSUE THREAD

**Issue by SpruceWillows** [clyall/FormEmailer#7]
Downloaded the zip and unpacked 5 files: 
about.html
Code.gs.txt
fix-sheet.html
install.html
settings.html
Opened files in TextEdit (Apple) but contents appear very incomplete or nonexistent. Only the code.gs appears complete. See attached screenshot. 
Thoughts?
Thanks!
![Screen Shot 2019-04-30 at 12 11 19 PM](https://user-images.githubusercontent.com/50148350/56976490-16bc5b80-6b41-11e9-9682-71e36df7e101.png)
![Screen Shot 2019-04-30 at 12 15 35 PM](https://user-images.githubusercontent.com/50148350/56976710-9813ee00-6b41-11e9-80c6-77bbf01ede21.png)

**Comment by clyall** [comment]
I zipped these on my Windows machine, I'll try and replicate tomorrow on my Mac and get back with ya

**Comment by clyall** [comment]
It looks like its a TextEdit issue. If you open up TextEdit > Preferences > Open and Save and check the option "Display HTML files as HTML code instead of formatted text".

These html files use Google Script templating, so TextEdit cannot parse them, which is why you saw the nearly blank file

<img width="425" alt="text-edit-settings" src="https://user-images.githubusercontent.com/3732992/57023013-c814cd00-6be5-11e9-8d35-411cd1dc5053.png">

**Comment by pparkey** [comment]
I also am having this issue.   The Code file is a text file, but the other 4 are all hyperlinks and loop back to the webpage of instructions.
